---
# Install newrelic server monitoring tool

- name: "newrelic_setup/tasks"
  debug:
    msg: "{{ prologue.split('\n') }}" 
  when: prologue is defined
  tags:
    - prolog

- include: newrelic-sysmond.yml

# The PHP newrelic components are only installed if explicitly
# set in the play
- include: newrelic-php5.yml
  when: newrelic_php_install == True
