---

- name: restart apache
  service:
    name: apache2
    state: restarted
  tags: newrelic

- name: restart monit
  service:
    name: monit
    state: restarted
  tags: newrelic

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted
  tags: newrelic
